import json
from typing import List
from models.llm_connector import query_llm
from utils.logger import logger

DECOMPOSITION_PROMPT = """
You are a factual claim extraction system. 
Your task is to take a piece of text (usually an answer generated by an AI) and decompose it into a list of atomic factual claims.

An atomic factual claim should:
1. Be a single, self-contained statement.
2. Contain enough context to be verifiable on its own.
3. Be a factual statement, not an opinion or filler text.

Output ONLY a JSON array of strings, where each string is an atomic claim.
Do not output any markdown formatting, just the raw JSON array.

Example input:
"The paper introduces Transformer, a novel architecture that relies entirely on self-attention mechanisms, dispensing with recurrence and convolutions. It achieved 28.4 BLEU on the WMT 2014 English-to-German translation task."

Example output:
[
    "The paper introduces a novel architecture called Transformer.",
    "The Transformer architecture relies entirely on self-attention mechanisms.",
    "The Transformer architecture dispenses with recurrence and convolutions.",
    "The Transformer achieved a BLEU score of 28.4 on the WMT 2014 English-to-German translation task."
]

Text to decompose:
{text}
"""

def decompose_into_claims(text: str, model_name: str = None) -> List[str]:
    """Decomposes a response text into a list of atomic claims using an LLM."""
    if not text or not text.strip():
        return []
        
    prompt = DECOMPOSITION_PROMPT.format(text=text)
    
    try:
        response = query_llm(
            prompt=prompt,
            model_name=model_name,
            system_prompt="You are a JSON-only API that extracts atomic factual claims from text. Output ONLY a valid JSON array of strings.",
            temperature=0.0 # Deterministic output
        )
        
        # Strip potential markdown formatting if the model ignored instructions
        response = response.strip()
        if response.startswith("```json"):
            response = response[7:]
        if response.startswith("```"):
            response = response[3:]
        if response.endswith("```"):
            response = response[:-3]
            
        claims = json.loads(response.strip())
        if isinstance(claims, list):
            return [str(c) for c in claims]
        return []
    except Exception as e:
        logger.error(f"Failed to decompose claims: {str(e)}")
        # Fallback: simple sentence splitting if LLM fails
        return [s.strip() for s in text.split('.') if len(s.strip()) > 10]
